import { integer } from './memory';
import type { GuestMemory } from './memory';

interface UnicornInstance {
  ctl_set_tcg_buffer_size(size: number): void;
  mem_map(address: number, size: number, permissions: number): void;
  mem_read(address: number, size: number): Uint8Array;
  mem_write(address: number, data: Uint8Array): void;
  reg_read_i64(register: number): bigint;
  reg_write_i64(register: number, value: bigint): void;
  hook_add(
    type: number,
    callback: (engine: unknown, address: bigint) => void,
    data: unknown,
    begin: number,
    end: number,
  ): unknown;
  hook_del(hook: unknown): void;
  emu_start(begin: number, end: number, timeout: number, count: number): void;
  emu_stop(): void;
  close(): void;
}

interface UnicornModule {
  Unicorn: new (architecture: number, mode: number) => UnicornInstance;
  [constant: string]: unknown;
}

export class Engine implements GuestMemory {
  private readonly instance: UnicornInstance;
  private readonly hooks: unknown[] = [];
  private fault: Error | null = null;

  private constructor(private readonly module: UnicornModule) {
    this.instance = new module.Unicorn(
      this.constant('ARCH_X86'),
      this.constant('MODE_64'),
    );
    // Upstream's 64-bit default reserves 1 GiB for translated code alone.
    // SAP needs a much smaller cache; keep mobile browser memory bounded.
    this.instance.ctl_set_tcg_buffer_size(32 << 20);
  }

  static async create(
    moduleURL = '/sap-engine/unicorn.mjs',
    options: Record<string, unknown> = {},
  ): Promise<Engine> {
    // This URL is always supplied by our worker, never by an Apple response.
    // The unminified module and WASM are generated by tools/sap-engine.
    const factory = await import(/* @vite-ignore */ moduleURL);
    return new Engine(await factory.default(options));
  }

  private constant(name: string): number {
    const value = this.module[name];
    if (typeof value !== 'number')
      throw new Error(`Missing emulator constant: ${name}`);
    return value;
  }

  map(address: number, size: number): void {
    this.instance.mem_map(address, size, this.constant('PROT_ALL'));
  }
  read(address: number, size: number): Uint8Array {
    return new Uint8Array(this.instance.mem_read(address, size));
  }
  write(address: number, data: Uint8Array): void {
    this.instance.mem_write(address, data);
  }
  register(name: string): bigint {
    return this.instance.reg_read_i64(this.constant(`X86_REG_${name}`));
  }
  setRegister(name: string, value: bigint | number): void {
    this.instance.reg_write_i64(
      this.constant(`X86_REG_${name}`),
      BigInt.asIntN(64, BigInt(value)),
    );
  }

  hook(begin: number, end: number, callback: (address: number) => void): void {
    this.hooks.push(
      this.instance.hook_add(
        this.constant('HOOK_CODE'),
        (_, address) => {
          try {
            callback(integer(address));
          } catch (error) {
            this.fault =
              error instanceof Error
                ? error
                : new Error('Guest service failed');
            this.instance.emu_stop();
          }
        },
        null,
        begin,
        end,
      ),
    );
  }

  run(begin: number, end: number): void {
    this.fault = null;
    try {
      // No timeout thread in WASM. The worker's owner enforces a wall-clock
      // deadline by terminating the worker, including runaway guest code.
      this.instance.emu_start(begin, end, 0, 0);
    } catch (error) {
      throw this.fault ?? new Error(`SAP emulator failed: ${String(error)}`);
    }
    if (this.fault) throw this.fault;
    if (integer(this.register('RIP')) !== end)
      throw new Error('SAP execution budget exceeded');
  }

  close(): void {
    for (const hook of this.hooks) this.instance.hook_del(hook);
    this.instance.close();
  }
}
